const nouvelle_partie = document.querySelector('.card-body .btn');
const stat_erreurs = document.querySelector('#errors');
const stat_streak = document.querySelector('#record');
const pendu = document.querySelector('#hangman');
const erreur1 = pendu.querySelector('#error-1');
const erreur2 = pendu.querySelector('#error-2');
const erreur3 = pendu.querySelector('#error-3');
const erreur4 = pendu.querySelector('#error-4');
const erreur5 = pendu.querySelector('#error-5');